## Exercise 1

## Perform the following matrix operations, when the operation is valid


In [44]:
import numpy as np

A = np.array([[2,4,3],[0,1,3]])
B = np.array([[-2,-1,3],[6,-7,7]])
C = np.array([[0,-6],[-3,-2],[-2,7]])
D = np.array([[1,2],[3,4],[2,4]])

SyntaxError: invalid syntax (<ipython-input-44-b2df920440e6>, line 2)

In [21]:
A

array([[2, 4, 3],
       [0, 1, 3]])

In [22]:
B

array([[-2, -1,  3],
       [ 6, -7,  7]])

In [23]:
C

array([[ 0, -6],
       [-3, -2],
       [-2,  7]])

In [24]:
D

array([[1, 2],
       [3, 4],
       [2, 4]])

In [15]:
#a) A+3B
a = A+3*B
a

array([[ -4,   1,  12],
       [ 18, -20,  24]])

In [18]:
#b) A+C (Not valid) 

In [19]:
#c) C-D
c = C-D
c

array([[-1, -8],
       [-6, -6],
       [-4,  3]])

In [25]:
#d) D+C
d = D+C
d

array([[ 1, -4],
       [ 0,  2],
       [ 0, 11]])

In [26]:
#e) A' + D
e = np.transpose(A)+D
e

array([[3, 2],
       [7, 5],
       [5, 7]])

In [27]:
#f) (A+B)' +2C
f = np.transpose(A+B) + 2*C
f

array([[  0,  -6],
       [ -3, -10],
       [  2,  24]])

In [28]:
#g) 3A + (B' +C)'
g = 3*A +np.transpose((np.transpose(B)+C))
g

array([[ 4,  8, 10],
       [ 0, -6, 23]])

In [30]:
#h) -4(A'+C)' + D
h = -4 * (np.transpose(np.transpose(A) + C)) + D
#Not Valid

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

## Exercise 3

## Perform the indicated matrix operations (tr(M) indicates the trace of matrix M)


In [49]:
A = np.array([[2,4],[0,3]])
B = np.array([[-2,-1],[6,7]])

In [32]:
A

array([[2, 4],
       [0, 3]])

In [33]:
B

array([[-2, -1],
       [ 6,  7]])

In [37]:
#tr(A)
a = np.trace(A)
a

5

In [39]:
#tr(-3A)
b = np.trace(-3*A)
b

-15

In [40]:
#tr(A+B)
c = np.trace(A+B)
c

10

In [41]:
#tr((A+B)')
d = np.trace(np.transpose(A+B))
d

10

In [45]:
#tr(B'+A)
e = np.trace(np.transpose(B)+A)
e

10

In [47]:
#tr(B+A')
f = np.trace(B+ np.transpose(A))
f

10